#!/usr/bin/perl
use strict;
use CGI ;

my $q = new CGI;
my $utcstart = $q->param('utcstart');
my $utcend = $q->param('utcend');
my $fpathrrd = $q->param('file');
my $bits= $q->param('bits');
my $zoom = $q->param('zoom');

print $q->header(-type=>'image/png', 
				 -expires => 'now',
				-Cache-Control=>'no-cache');

my (@header_str,@def_str,@data_str,@comment_str);

@header_str = (
		"--title","Traffic Stats",
		"--imgformat","PNG",
		"--start","$utcstart",
		"--end","$utcend",
		"--color","FRAME#FFFFFF",
        "--color","SHADEA#FFFFFF",
   		"--color","SHADEB#FFFFFF",
      	"--color","BACK#FFFFFF",
);

if ($zoom == 1) {
	push @header_str,("-w","600","-h","150");

}

if ($bits == 1){
	@def_str = ( 
	"DEF:indatabits=$fpathrrd:in:AVERAGE",
    "DEF:outdatabits=$fpathrrd:out:AVERAGE",
    "CDEF:indata=indatabits,8,*",
    "CDEF:outdata=outdatabits,8,*",
    "CDEF:averagein=indata,UN,0,indata,IF",
    "CDEF:averageout=outdata,UN,0,outdata,IF"
	);
	push @header_str,(
	"--vertical-label","Bits per second",
	"--base","1000",
	"--units-exponent","3"
	);
}else {
	@def_str =(
	"DEF:indatabytes=$fpathrrd:in:AVERAGE",
    "DEF:outdatabytes=$fpathrrd:out:AVERAGE",
    "CDEF:indata=indatabytes",
    "CDEF:outdata=outdatabytes",
    "CDEF:averagein=indatabytes,UN,0,indatabytes,IF",
    "CDEF:averageout=outdatabytes,UN,0,outdatabytes,IF",
	);
	push @header_str,("--vertical-label","Bytes per second");
}

@data_str = (
	"AREA:averagein#00CC00:In",
	"GPRINT:indata:AVERAGE:Avg\\:%8.2lf%s",
	"GPRINT:indata:MIN:Min\\:%8.2lf%s",
	"GPRINT:indata:MAX:Max\\:%8.2lf%s",
	"GPRINT:indata:LAST:Current\\:%8.2lf%s\\n",
	"LINE1:averageout#0000FF:Out",
    "GPRINT:outdata:AVERAGE:Avg\\:%8.2lf%s",
    "GPRINT:outdata:MIN:Min\\:%8.2lf%s",
    "GPRINT:outdata:MAX:Max\\:%8.2lf%s",
    "GPRINT:outdata:LAST:Current\\:%8.2lf%s\\n"
);

@comment_str = ("COMMENT:Generated by sasacct http://rousse.pm.org/sasacct\\c");

&show_graph();

sub show_graph {
	use RRDs;
	RRDs::graph("-",@header_str,@def_str,@data_str,@comment_str);
}
